### ISSUE TITLE
fix the fucking hey code

### ISSUE THREAD

**Issue by AM7999** [clothing-hanger/CH-Engine#2]
fix the fucking hey code

**Comment by HTV04** [comment]
#1 fixes this severe issue, but @clothing-hanger doesn't want to merge it
![image](https://user-images.githubusercontent.com/53527582/158037314-c5aaa46a-9d77-4525-8f96-9d3559857568.png)

**Comment by GameVasion** [comment]
@clothing-hanger MERGE #1

**Comment by clothing-hanger** [comment]
STOP

**Comment by GameVasion** [comment]
Reopen

**Comment by GameVasion** [comment]
hi @clothing-hanger please merge #1

**Comment by AM7999** [comment]
FUCKING MERGE THE PR
